# Generated by Django 4.2.3 on 2023-07-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(default='', max_length=254)),
                ('etiqueta', models.JSONField(blank=True, default=str, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('telefono', models.PositiveIntegerField(default=99999999)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('apellido', models.CharField(default='', max_length=255)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], default='Masculino', max_length=14)),
                ('fecha_nacimiento', models.DateField(default='1999-01-01')),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=254)),
                ('seguidores', models.JSONField(default=[])),
                ('seguidos', models.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Tendencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionSeguidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='twitter.usuario')),
                ('seguidores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='twitter.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='mencion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menciona', to='twitter.usuario'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='republicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='republica', to='twitter.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizada', to='twitter.usuario'),
        ),
        migrations.CreateModel(
            name='MensajePriv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.CharField(default='', max_length=254)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emite', to='twitter.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to='twitter.usuario')),
            ],
        ),
    ]
