# Generated by Django 4.2.3 on 2023-07-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='seguidos',
        ),
    ]
