# Generated by Django 4.2.3 on 2023-07-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_remove_usuario_seguidores_remove_usuario_seguidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajepriv',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
