# Generated by Django 4.2.3 on 2023-07-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_mensajepriv_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
