# Generated by Django 4.2.3 on 2023-07-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_publicacion_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
