# Generated by Django 4.2.3 on 2023-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_alter_publicacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
