# Generated by Django 3.1.3 on 2021-06-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(default=5, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(default='', max_length=255)),
                ('telefono', models.PositiveIntegerField(default=99999999)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('apellido', models.CharField(default='', max_length=255)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], default='Masculino', max_length=14)),
                ('fechaNac', models.DateField(default='1930-01-01')),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=254)),
                ('prueba', models.TextField(default='as')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(default='', max_length=254)),
                ('etiqueta', models.JSONField(default=None)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(default=5, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(default='', max_length=255)),
                ('telefono', models.PositiveIntegerField(default=99999999)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('apellido', models.CharField(default='', max_length=255)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], default='Masculino', max_length=14)),
                ('fechaNac', models.DateField(default='1930-01-01')),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=254)),
                ('seguidores', models.JSONField(default=None)),
                ('seguidos', models.JSONField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tendencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='mencion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menciona', to='twitter.usuario'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='republicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='republica', to='twitter.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizada', to='twitter.usuario'),
        ),
        migrations.CreateModel(
            name='MensajePriv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.CharField(default='', max_length=254)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emite', to='twitter.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to='twitter.usuario')),
            ],
        ),
    ]
