# Generated by Django 3.1.3 on 2021-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidos',
            field=models.JSONField(default=None),
        ),
    ]
