# Generated by Django 3.1.3 on 2021-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210531_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='etiqueta',
            field=models.JSONField(default=None),
        ),
    ]
